"""add display_order to my_ship

Revision ID: 0e1177512143
Revises: 
Create Date: 2026-03-07 15:11:45.905040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1177512143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_ships', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
