"""add stats to component

Revision ID: 126ab319ae79
Revises: 0e1177512143
Create Date: 2026-03-07 15:36:14.878228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126ab319ae79'
down_revision = '0e1177512143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_column('stats')

    # ### end Alembic commands ###
