"""add weapon mount grouping columns

Revision ID: 560731888810
Revises: 636990448b90
Create Date: 2026-03-07 18:51:40.869094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560731888810'
down_revision = '636990448b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_default_loadout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mount_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mount_group', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mount_label', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_default_loadout', schema=None) as batch_op:
        batch_op.drop_column('mount_label')
        batch_op.drop_column('mount_group')
        batch_op.drop_column('mount_type')

    # ### end Alembic commands ###
