"""add weapon stats column

Revision ID: 636990448b90
Revises: 126ab319ae79
Create Date: 2026-03-07 18:22:48.739192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636990448b90'
down_revision = '126ab319ae79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.drop_column('stats')

    # ### end Alembic commands ###
