"""add image_path to ship

Revision ID: 6b9f71a72e28
Revises: ac3d6580dd8d
Create Date: 2026-03-10 08:59:17.642739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9f71a72e28'
down_revision = 'ac3d6580dd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
