"""add power fields to ship

Revision ID: 8e4255d232da
Revises: 560731888810
Create Date: 2026-03-09 18:06:09.227164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4255d232da'
down_revision = '560731888810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power_generation_pips', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('power_segments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_column('power_segments')
        batch_op.drop_column('power_generation_pips')

    # ### end Alembic commands ###
