"""add ship_stats to ship

Revision ID: ac3d6580dd8d
Revises: 8e4255d232da
Create Date: 2026-03-09 20:26:03.353648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3d6580dd8d'
down_revision = '8e4255d232da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_column('ship_stats')

    # ### end Alembic commands ###
